apiVersion: v1
kind: Service
metadata:
  name: timesheetgen-service
  namespace: prod
spec:
  type: NodePort
  selector:
    app: timesheetgen
  ports:
    - port: 80
      targetPort: 8082
      nodePort: 30008
